FROM maven:3.8.5-openjdk-17 as BUILDER

WORKDIR /usr/src/app

COPY ./pom.xml ./pom.xml
COPY ./src ./src

RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests

FROM openjdk:17-alpine

ENV SERVER_PORT=80

WORKDIR /usr/src/app

COPY --from=BUILDER /usr/src/app/target/api*.jar ./api.jar

EXPOSE ${SERVER_PORT}

ENTRYPOINT [ "java", "-jar", "api.jar" ]